os.path: refactor: use sep instead of literal /
micropython/micropython-lib pull request #730
Opened 2023-09-14 12:44 UTC by scivision

2023-10-04 01:52 UTC, dpgeorge commented
Thanks for the contribution.  Can you please explain what prompted this change and why it's better this way?

2023-10-18 00:18 UTC, projectgus requested changes
Change LGTM apart from one small fix needed. However like @dpgeorge I'm curious what the motivation for making it was. (Windows, maybe?)

2023-10-18 00:18 UTC, projectgus commented on python-stdlib/os-path/os/path.py
> +        return bytes(sep).join(args)
This line will raise an exception:

```
MicroPython v1.20.0-330-g076bfc7ed8-dirty on 2023-09-26; linux [GCC 13.2.1] version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> bytes("/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: string argument without an encoding
>>> "/".encode()
b'/'
```

2026-06-29 14:37 UTC, dpgeorge commented
Closing due to inactivity.

2026-06-29 14:37 UTC, closed without merging