python-ecosys/aiohttp: Fix binary data treatment.
micropython/micropython-lib pull request #782
Opened 2024-01-03 02:01 UTC by Carglglz

Fixes #781

2024-01-04 16:04 UTC, bixb922 requested changes
I'd suggest not to specify "latin-1" as encoding. This parameter is AFAIK ignored for .encode(), and the encoding for JSON has to be UTF-8, which is the default for .encode()

2024-02-07 01:57 UTC, dpgeorge commented on python-ecosys/aiohttp/aiohttp/__init__.py
> +        return (await self.read(sz=int(self.headers.get("Content-Length", -1)))).decode(encoding)
I suggest just using positional arguments (not doing `sz=`) because it will make slightly smaller and slightly faster code.

2024-02-07 01:57 UTC, dpgeorge commented on python-ecosys/aiohttp/aiohttp/__init__.py
> +        return _json.loads(await self.read(sz=int(self.headers.get("Content-Length", -1))))
Suggest using positional arguments for `read()`.

2024-02-08 08:05 UTC, merged

2024-02-08 08:05 UTC, dpgeorge commented
Thanks for updating, now merged.